/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;

/**
 *
 * @author lizsotomayor
 */
public class AdoptPage extends javax.swing.JFrame {

    /**
     * Creates new form AdoptPage
     */
    public AdoptPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdoptButton = new javax.swing.JButton();
        EnterSsn = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EnterPet = new javax.swing.JTextField();
        EnterId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        AdoptButton.setText("Adopt");
        AdoptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdoptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AdoptButton);
        AdoptButton.setBounds(247, 236, 72, 23);

        EnterSsn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterSsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSsnActionPerformed(evt);
            }
        });
        jPanel1.add(EnterSsn);
        EnterSsn.setBounds(207, 189, 147, 29);

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        UserLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        UserLabel.setText("Application Id");
        jPanel2.add(UserLabel);
        UserLabel.setBounds(90, 40, 140, 24);

        PassLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel.setText("Pet to Be Adopted");
        jPanel2.add(PassLabel);
        PassLabel.setBounds(60, 100, 150, 24);

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        jLabel1.setText("Approving Employee SSN");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 140, 260, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 36, 189, 190);

        EnterPet.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPetActionPerformed(evt);
            }
        });
        jPanel1.add(EnterPet);
        EnterPet.setBounds(207, 127, 147, 29);

        EnterId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterIdActionPerformed(evt);
            }
        });
        jPanel1.add(EnterId);
        EnterId.setBounds(207, 65, 147, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(394, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterSsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSsnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSsnActionPerformed

    private void EnterIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterIdActionPerformed

    private void AdoptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdoptButtonActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";
        String user = "postgres";
        String query = "insert into adopt(applicationid, petname, adoption_date, ssn) values(?, ?, ?, ?)";
        String id = EnterId.getText();
        String pet = EnterPet.getText();
        String employee_ssn = EnterSsn.getText();
        
       java.util.Date d1 = new java.util.Date();

       java.sql.Date sqlDate = new java.sql.Date(d1.getTime());    
      
        
        try{
            Connection conn = DriverManager.getConnection(url, user, null);
            Statement stmnt = conn.createStatement();
            PreparedStatement stm = conn.prepareCall(query);
            
             try {
                    int app_id = Integer.parseInt(id);
                    stm.setInt(1, app_id);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid integer for application ID.");
                }
            
            stm.setString(2, pet);
            stm.setDate(3, sqlDate);
            stm.setString(4, employee_ssn);
            stm.execute();

            JOptionPane.showMessageDialog(this, "Adoption approved successfully.");

            EnterId.setText(null);
            EnterPet.setText(null);
            EnterSsn.setText(null);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
        }
    }//GEN-LAST:event_AdoptButtonActionPerformed

    private void EnterPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdoptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdoptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdoptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdoptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdoptPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdoptButton;
    private javax.swing.JTextField EnterId;
    private javax.swing.JTextField EnterPet;
    private javax.swing.JTextField EnterSsn;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
