/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author lizsotomayor
 */
public class CreateEmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form CreateEmployeePage
     */
    public CreateEmployeePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        EnterSSN = new javax.swing.JTextField();
        EnterFN = new javax.swing.JTextField();
        EnterLN = new javax.swing.JTextField();
        EnterDOB = new javax.swing.JTextField();
        EnterGender = new javax.swing.JTextField();
        EnterPosition = new javax.swing.JTextField();
        EnterSalary = new javax.swing.JTextField();
        EnterAvailability = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        EnterSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSSNActionPerformed(evt);
            }
        });
        jPanel1.add(EnterSSN);
        EnterSSN.setBounds(123, 30, 207, 22);

        EnterFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterFNActionPerformed(evt);
            }
        });
        jPanel1.add(EnterFN);
        EnterFN.setBounds(123, 65, 207, 22);

        EnterLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterLNActionPerformed(evt);
            }
        });
        jPanel1.add(EnterLN);
        EnterLN.setBounds(123, 100, 207, 22);

        EnterDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterDOBActionPerformed(evt);
            }
        });
        jPanel1.add(EnterDOB);
        EnterDOB.setBounds(123, 135, 207, 22);

        EnterGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterGenderActionPerformed(evt);
            }
        });
        jPanel1.add(EnterGender);
        EnterGender.setBounds(123, 172, 207, 22);

        EnterPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPositionActionPerformed(evt);
            }
        });
        jPanel1.add(EnterPosition);
        EnterPosition.setBounds(123, 207, 207, 22);

        EnterSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSalaryActionPerformed(evt);
            }
        });
        jPanel1.add(EnterSalary);
        EnterSalary.setBounds(123, 242, 207, 22);

        EnterAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterAvailabilityActionPerformed(evt);
            }
        });
        jPanel1.add(EnterAvailability);
        EnterAvailability.setBounds(123, 277, 207, 22);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton);
        AddButton.setBounds(190, 320, 72, 23);

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel2.setText("SSN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(64, 23, 27, 18);

        jLabel3.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(31, 56, 64, 18);

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel1.setText("Last Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(34, 89, 63, 18);

        jLabel7.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel7.setText("DOB");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(64, 128, 28, 18);

        jLabel6.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(54, 167, 42, 18);

        jLabel4.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel4.setText("Position");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(48, 200, 47, 18);

        jLabel5.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel5.setText("Salary");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(62, 233, 37, 18);

        jLabel8.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel8.setText("Availability");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 270, 61, 18);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 100, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(408, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSSNActionPerformed

    private void EnterFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterFNActionPerformed

    private void EnterLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterLNActionPerformed

    private void EnterDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterDOBActionPerformed

    private void EnterGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterGenderActionPerformed

    private void EnterPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPositionActionPerformed

    private void EnterSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSalaryActionPerformed

    private void EnterAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterAvailabilityActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";
        String user = "postgres";
        String query = "insert into employees(ssn, first_name, last_name, dob, gender, position, salary, availability) values(?, ?, ?, ?, ?, ?, ?, ?)";
        String ssn = EnterSSN.getText();
        String fn = EnterFN.getText();
        String ln = EnterLN.getText();
        String stringdob = EnterDOB.getText();
        String gender = EnterGender.getText();
        String position = EnterPosition.getText();
        String stringsalary = EnterSalary.getText();
        String availability = EnterAvailability.getText();
        try{
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(stringdob);
            java.sql.Date dob = new java.sql.Date(date.getTime());
            double salary = Double.parseDouble(stringsalary);
        try{
            Connection conn = DriverManager.getConnection(url, user, null);
            Statement stmnt = conn.createStatement();
            PreparedStatement stm = conn.prepareCall(query);
            
            
            stm.setString(1, ssn);
            stm.setString(2, fn);
            stm.setString(3, ln);
            stm.setDate(4, dob);
            stm.setString(5, gender);
            stm.setString(6, position);
            stm.setDouble(7, salary);
            stm.setString(8, availability);
            stm.execute();
            JOptionPane.showMessageDialog(this, "Employee added successfully.");
            
            EnterSSN.setText(null);
            EnterFN.setText(null);
            EnterLN.setText(null);
            EnterDOB.setText(null);
            EnterGender.setText(null);
            EnterPosition.setText(null);
            EnterSalary.setText(null);
            EnterAvailability.setText(null);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
        }}
        catch(java.text.ParseException ex){
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use yyyy-mm-dd");
        }
         catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid salary format. Please enter a numeric value.");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
    }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField EnterAvailability;
    private javax.swing.JTextField EnterDOB;
    private javax.swing.JTextField EnterFN;
    private javax.swing.JTextField EnterGender;
    private javax.swing.JTextField EnterLN;
    private javax.swing.JTextField EnterPosition;
    private javax.swing.JTextField EnterSSN;
    private javax.swing.JTextField EnterSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
