/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author lizsotomayor
 */
public class CreateUserPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateUserPage
     */
    public CreateUserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EnterPassword = new javax.swing.JTextField();
        EnterRole = new javax.swing.JTextField();
        EnterSSN = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EnterUsername = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        EnterPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPasswordActionPerformed(evt);
            }
        });

        EnterRole.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterRoleActionPerformed(evt);
            }
        });

        EnterSSN.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSSNActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        UserLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 18)); // NOI18N
        UserLabel.setText("Username");
        jPanel2.add(UserLabel);
        UserLabel.setBounds(10, 40, 100, 28);

        PassLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 18)); // NOI18N
        PassLabel.setText("Password");
        jPanel2.add(PassLabel);
        PassLabel.setBounds(20, 110, 80, 28);

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 18)); // NOI18N
        jLabel1.setText("Role");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 180, 61, 30);

        jLabel7.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 18)); // NOI18N
        jLabel7.setText("SSN");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 240, 60, 40);

        EnterUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        EnterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterUsernameActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterRole, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(AddButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(EnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(EnterRole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(EnterSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(AddButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(365, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterUsernameActionPerformed

    private void EnterPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterPasswordActionPerformed

    private void EnterRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterRoleActionPerformed

    private void EnterSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSSNActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";
        String user = "postgres";
        String query = "insert into users(username, password, role, ssn) values(?, ?, ?, ?)";
        String username = EnterUsername.getText();
        String password = EnterPassword.getText();
        String role = EnterRole.getText();
        String ssn = EnterSSN.getText();
        try{
            Connection conn = DriverManager.getConnection(url, user, null);
            Statement stmnt = conn.createStatement();
            PreparedStatement stm = conn.prepareCall(query);

            stm.setString(1, username);
            stm.setString(2, password);
            stm.setString(3, role);
            stm.setString(4, ssn);
            stm.execute();

            JOptionPane.showMessageDialog(this, "User added successfully.");

            EnterUsername.setText(null);
            EnterPassword.setText(null);
            EnterRole.setText(null);
            EnterSSN.setText(null);
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
            }
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField EnterPassword;
    private javax.swing.JTextField EnterRole;
    private javax.swing.JTextField EnterSSN;
    private javax.swing.JTextField EnterUsername;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
