
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lizsotomayor
 */
public class NewApplication extends javax.swing.JFrame {

    /**
     * Creates new form NewApplication
     */
    public NewApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ApplyButton = new javax.swing.JButton();
        ssn = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        PassLabel1 = new javax.swing.JLabel();
        PassLabel2 = new javax.swing.JLabel();
        PassLabel3 = new javax.swing.JLabel();
        PassLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        petname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        bio = new javax.swing.JTextField();
        otherpets = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        ApplyButton.setText("Apply");
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ApplyButton);
        ApplyButton.setBounds(250, 350, 72, 23);

        ssn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });
        jPanel1.add(ssn);
        ssn.setBounds(210, 190, 147, 29);

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        UserLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        UserLabel.setText("Pet Name");
        jPanel2.add(UserLabel);
        UserLabel.setBounds(90, 30, 140, 24);

        PassLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel.setText("Any Other Pets");
        jPanel2.add(PassLabel);
        PassLabel.setBounds(80, 260, 180, 50);

        PassLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel1.setText("First Name");
        jPanel2.add(PassLabel1);
        PassLabel1.setBounds(90, 80, 150, 24);

        PassLabel2.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel2.setText("Last Name");
        jPanel2.add(PassLabel2);
        PassLabel2.setBounds(90, 130, 150, 24);

        PassLabel3.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel3.setText("SSN");
        jPanel2.add(PassLabel3);
        PassLabel3.setBounds(110, 180, 150, 24);

        PassLabel4.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel4.setText("Brief Bio");
        jPanel2.add(PassLabel4);
        PassLabel4.setBounds(100, 230, 150, 24);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 16, 189, 380);

        firstname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname);
        firstname.setBounds(210, 90, 147, 30);

        petname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        petname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petnameActionPerformed(evt);
            }
        });
        jPanel1.add(petname);
        petname.setBounds(210, 40, 147, 29);

        lastname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(lastname);
        lastname.setBounds(210, 140, 147, 29);

        bio.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioActionPerformed(evt);
            }
        });
        jPanel1.add(bio);
        bio.setBounds(210, 240, 147, 29);

        otherpets.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        otherpets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherpetsActionPerformed(evt);
            }
        });
        jPanel1.add(otherpets);
        otherpets.setBounds(210, 290, 147, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(411, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";
        String user = "postgres";
        String query = "insert into applications(applicationid, ssn, first_name, last_name, petname, date, bio, other_pets ) values(?, ?, ?, ?, ?, ?, ?, ?)";
        String query2 = "select MAX(applicationid) AS max_id FROM applications";
        
        
        String pet = petname.getText();
        String first_name = firstname.getText();
        String last_name = lastname.getText();
        String app_ssn = ssn.getText();
        String app_bio = bio.getText();
        String other_pets = otherpets.getText();
        

        java.util.Date d1 = new java.util.Date();

        java.sql.Date sqlDate = new java.sql.Date(d1.getTime());

        try{
            Connection conn = DriverManager.getConnection(url, user, null);
            Statement stmnt = conn.createStatement();
            PreparedStatement stm = conn.prepareCall(query);
            
            int app_id = 1;
            try (Statement counter = conn.createStatement(); 
                ResultSet rs = counter.executeQuery(query2)) {
                if (rs.next()) {
                    app_id = rs.getInt("max_id") + 1;
                }
                rs.close();
                counter.close();
            }
            stm.setInt(1, app_id);
            /*
            try {
                int app_id = Integer.parseInt(id);
                stm.setInt(1, app_id);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Please enter a valid integer for application ID.");
            }
            */
            
            stm.setString(2, app_ssn);
            stm.setString(3, first_name);
            stm.setString(4, last_name);
            stm.setString(5, pet);
            stm.setDate(6, sqlDate);
            stm.setString(7, app_bio);
            stm.setString(8, other_pets);
            stm.execute();

            JOptionPane.showMessageDialog(this, "Application Successful");

            petname.setText(null);
            firstname.setText(null);
            ssn.setText(null);
            lastname.setText(null);
            bio.setText(null);
            otherpets.setText(null);
            
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
        }
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void petnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petnameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bioActionPerformed

    private void otherpetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherpetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherpetsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel PassLabel1;
    private javax.swing.JLabel PassLabel2;
    private javax.swing.JLabel PassLabel3;
    private javax.swing.JLabel PassLabel4;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField bio;
    private javax.swing.JTextField firstname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField otherpets;
    private javax.swing.JTextField petname;
    private javax.swing.JTextField ssn;
    // End of variables declaration//GEN-END:variables
}
