
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDate;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BloodPanther
 */
public class NewDonation extends javax.swing.JFrame {

    /**
     * Creates new form NewDonation
     */
    public NewDonation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NewDonation = new javax.swing.JButton();
        donationamount = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        NewDonation.setText("Add Donation");
        NewDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDonationActionPerformed(evt);
            }
        });
        jPanel1.add(NewDonation);
        NewDonation.setBounds(227, 236, 120, 23);

        donationamount.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        donationamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationamountActionPerformed(evt);
            }
        });
        jPanel1.add(donationamount);
        donationamount.setBounds(210, 190, 147, 29);

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        UserLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        UserLabel.setText("First Name");
        jPanel2.add(UserLabel);
        UserLabel.setBounds(90, 20, 140, 24);

        PassLabel.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        PassLabel.setText("Last Name");
        jPanel2.add(PassLabel);
        PassLabel.setBounds(100, 80, 150, 24);

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 15)); // NOI18N
        jLabel1.setText("Donation Amount");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 120, 260, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 56, 189, 170);

        lastname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(lastname);
        lastname.setBounds(210, 130, 147, 29);

        firstname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname);
        firstname.setBounds(210, 70, 147, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(437, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDonationActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";
        String user = "postgres";
        String donators_insert = "INSERT INTO donators(donatorid, first_name, last_name) values(?, ?, ?)";
        String donations_insert = "INSERT INTO donations(donationid, amount, date, donatorid) values(?, ?, ?, ?)";
        String donator_check = "SELECT donatorid FROM donators WHERE first_name = ? AND last_name = ?";
        String max_donatorid = "SELECT MAX(donatorid) AS donator_max FROM donators";
        String max_donationid = "SELECT MAX(donationid) AS donation_max FROM donations";
        
        
        String fnameIn = firstname.getText();
        String lnameIn = lastname.getText();
        int dAmount = Integer.parseInt(donationamount.getText());
        
        
        java.util.Date d1 = new java.util.Date();
        java.sql.Date sqlDate = new java.sql.Date(d1.getTime());
        
    Connection conn = null;
    PreparedStatement checkStmt = null;
    PreparedStatement donatorsInsertStmt = null;
    PreparedStatement donationsInsertStmt = null;
    Statement donatorMaxStmt = null;
    Statement donationMaxStmt = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    
    try {
        conn = DriverManager.getConnection(url, user, null);
        checkStmt = conn.prepareStatement(donator_check);
        checkStmt.setString(1, fnameIn);
        checkStmt.setString(2, lnameIn);
        rs = checkStmt.executeQuery();
        
        int donatorId;
        if (rs.next()) {
            donatorId = rs.getInt("donatorid");
        } else {
            
            donatorMaxStmt = conn.createStatement();
            rs2 = donatorMaxStmt.executeQuery(max_donatorid);
            if (rs2.next()) {
                donatorId = rs2.getInt("donator_max") + 1;
            } else {
                donatorId = 1; 
            }
            rs2.close();
            donatorMaxStmt.close();
            
            donatorsInsertStmt = conn.prepareStatement(donators_insert);
            donatorsInsertStmt.setInt(1, donatorId);
            donatorsInsertStmt.setString(2, fnameIn);
            donatorsInsertStmt.setString(3, lnameIn);
            donatorsInsertStmt.executeUpdate();
        }
        
        
        donationMaxStmt = conn.createStatement();
        rs3 = donationMaxStmt.executeQuery(max_donationid);
        int donationId;
        if (rs3.next()) {
            donationId = rs3.getInt("donation_max") + 1;
        } else {
            donationId = 1;  
        }
        rs3.close();
        donationMaxStmt.close();
        
        donationsInsertStmt = conn.prepareStatement(donations_insert);
        donationsInsertStmt.setInt(1, donationId);
        donationsInsertStmt.setInt(2, dAmount);
        donationsInsertStmt.setDate(3, sqlDate);
        donationsInsertStmt.setInt(4, donatorId);
        donationsInsertStmt.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Donation added successfully");

            firstname.setText(null);
            lastname.setText(null);
            donationamount.setText(null);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
        }
    }//GEN-LAST:event_NewDonationActionPerformed

    private void donationamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donationamountActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDonation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDonation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewDonation;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField donationamount;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    // End of variables declaration//GEN-END:variables
}
