/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lizsotomayor
 */

import javax.swing.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

public class NewIntake extends javax.swing.JFrame {

    /**
     * Creates new form NewIntake
     */
    public NewIntake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EnterName = new javax.swing.JTextField();
        EnterSpecies = new javax.swing.JTextField();
        EnterBreed = new javax.swing.JTextField();
        EnterWeight = new javax.swing.JTextField();
        EnterGender = new javax.swing.JTextField();
        EnterColor = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EnterNotes = new javax.swing.JTextField();
        EnterAllergies = new javax.swing.JTextField();
        EnterDate = new javax.swing.JTextField();
        EnterStatus = new javax.swing.JTextField();

        jLabel10.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel10.setText("Status");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setLayout(null);

        EnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNameActionPerformed(evt);
            }
        });
        jPanel1.add(EnterName);
        EnterName.setBounds(120, 40, 210, 22);

        EnterSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterSpeciesActionPerformed(evt);
            }
        });
        jPanel1.add(EnterSpecies);
        EnterSpecies.setBounds(120, 70, 210, 22);

        EnterBreed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBreedActionPerformed(evt);
            }
        });
        jPanel1.add(EnterBreed);
        EnterBreed.setBounds(120, 100, 210, 22);

        EnterWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterWeightActionPerformed(evt);
            }
        });
        jPanel1.add(EnterWeight);
        EnterWeight.setBounds(120, 130, 210, 22);

        EnterGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterGenderActionPerformed(evt);
            }
        });
        jPanel1.add(EnterGender);
        EnterGender.setBounds(120, 160, 210, 22);

        EnterColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterColorActionPerformed(evt);
            }
        });
        jPanel1.add(EnterColor);
        EnterColor.setBounds(120, 190, 210, 22);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton);
        AddButton.setBounds(190, 370, 72, 23);

        jPanel2.setBackground(new java.awt.Color(250, 250, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please Enter:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("YuMincho +36p Kana", 3, 13))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 30, 34, 18);

        jLabel3.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel3.setText("Species");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 60, 47, 18);

        jLabel1.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel1.setText("Breed");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 90, 34, 18);

        jLabel7.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel7.setText("Weight");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 120, 60, 18);

        jLabel6.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 150, 42, 18);

        jLabel4.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel4.setText("Allergies");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 210, 60, 18);

        jLabel5.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel5.setText("Color");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 180, 30, 18);

        jLabel8.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel8.setText("Notes");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 290, 80, 50);

        jLabel9.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel9.setText("Intake Date");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 220, 80, 70);

        jLabel11.setFont(new java.awt.Font("YuMincho +36p Kana", 0, 13)); // NOI18N
        jLabel11.setText("Status");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 250, 80, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 100, 340);
        jPanel1.add(EnterNotes);
        EnterNotes.setBounds(120, 310, 210, 22);

        EnterAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterAllergiesActionPerformed(evt);
            }
        });
        jPanel1.add(EnterAllergies);
        EnterAllergies.setBounds(120, 220, 210, 22);
        jPanel1.add(EnterDate);
        EnterDate.setBounds(120, 250, 210, 22);
        jPanel1.add(EnterStatus);
        EnterStatus.setBounds(120, 280, 210, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterNameActionPerformed

    private void EnterSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterSpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterSpeciesActionPerformed

    private void EnterBreedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBreedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterBreedActionPerformed

    private void EnterWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterWeightActionPerformed

    private void EnterGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterGenderActionPerformed

    private void EnterColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterColorActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String url = "jdbc:postgresql://localhost:5432/humane_society";

        String user = "postgres";
        String query = "insert into pets(petname, species, type, gender, weight, color, allergies, intake_date, status, notes) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        String name = EnterName.getText();
        String species = EnterSpecies.getText();
        String breed = EnterBreed.getText();
        String gender = EnterGender.getText();
        String stringweight = EnterWeight.getText();
        String color = EnterColor.getText();
        String allergies = EnterAllergies.getText();
        String stringdate = EnterDate.getText();
        String status = EnterStatus.getText();
        String notes = EnterNotes.getText();
        
        try{
            double weight = Double.parseDouble(stringweight);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(stringdate);
            java.sql.Date intake_date = new java.sql.Date(date.getTime());
            
            try{
                Connection conn = DriverManager.getConnection(url, user, null);
                Statement stmnt = conn.createStatement();
                PreparedStatement stm = conn.prepareCall(query);

                stm.setString(1, name);
                stm.setString(2, species);
                stm.setString(3, breed);
                stm.setString(4, gender);
                stm.setDouble(5, weight);
                stm.setString(6, color);
                stm.setString(7, allergies);
                stm.setDate(8, intake_date);
                stm.setString(9, status);
                stm.setString(10, notes);
                stm.execute();
                JOptionPane.showMessageDialog(this, "Pet added successfully.");

                EnterName.setText(null);
                EnterSpecies.setText(null);
                EnterBreed.setText(null);
                EnterWeight.setText(null);
                EnterGender.setText(null);
                EnterColor.setText(null);
                EnterAllergies.setText(null);
                EnterDate.setText(null);
                EnterStatus.setText(null);
                EnterNotes.setText(null);

            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error executing SQL: " + ex.getMessage());
            }}
            catch(java.text.ParseException ex){
                JOptionPane.showMessageDialog(this, "Invalid date format. Please use yyyy-mm-dd");
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid weight format. Please enter a numeric value.");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());
            }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void EnterAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterAllergiesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewIntake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewIntake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField EnterAllergies;
    private javax.swing.JTextField EnterBreed;
    private javax.swing.JTextField EnterColor;
    private javax.swing.JTextField EnterDate;
    private javax.swing.JTextField EnterGender;
    private javax.swing.JTextField EnterName;
    private javax.swing.JTextField EnterNotes;
    private javax.swing.JTextField EnterSpecies;
    private javax.swing.JTextField EnterStatus;
    private javax.swing.JTextField EnterWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
